services:
  web:
    image: mariavch/user-directory-web:latest
    build: .
    command: gunicorn --bind 0.0.0.0:8000 user_directory.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./logs:/app/logs
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-adminpassword}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.45.0  # Use a specific version
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9093:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  grafana_data:
